export enum CategoryEnum {
    AssetManagement = 'assetManagement',
    BusinessService = 'businessService',
    Defi = 'defi',
    Education = 'education',
    Entertainment = 'entertainment',
    Enviroment = 'enviroment',
    Events = 'events',
    Governance = 'governance',
    GrantsAndPhilantrophy = 'grantsAndPhilantrophy',
    HealthAndWellness = 'healthAndWellness',
    Identity = 'identity',
    Marketplace = 'marketplace',
    NewsAndMedia = 'newsAndMedia',
    Places = 'places',
    ScienceAndTech = 'scienceAndTech',
    Social = 'social',
    SupplyChain = 'supplyChain',
    Work = 'work',
    Other = 'other',
}
